### PR TITLE
refactor:Tidy up scalar module

### PR DESCRIPTION
**Pull request by winrhcp**
Rationale for this change
Mentioned in https://github.com/spaceandtimelabs/sxt-proof-of-sql/issues/234

What changes are included in this PR?
 Combine any logic held within the four files "mont_scalar", "mont_scalar_from", "mont_scalar_test", "mont_scalar_from_test" into two files "mont_scalar" and "mont_scalar_test"

/claim #234

### CODE REVIEW

**Comment by JayWhite2357** [comment]
Thanks for the PR!

It looks like the CI isn't passing. To expedite the review process, you can run the CI locally to ensure you fix the formatting/clippy issues: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md#user-content-code-quality-checks.

**Comment by winrhcp** [comment]
> Thanks for the PR!
> 
> It looks like the CI isn't passing. To expedite the review process, you can run the CI locally to ensure you fix the formatting/clippy issues: https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md#user-content-code-quality-checks.

Thank you for the feedback! I’ll run the CI checks locally again to address the formatting and Clippy issues as suggested. I’ll make sure everything is in order before resubmitting the PR.

**Review by stuarttimwhite — APPROVED** [review]
Looks good!

**Review by JayWhite2357 — APPROVED** [review]
Thank you! Looks good!

@winrhcp just to be extra clear: the second task (Move the Scalar trait to its own "scalar" file within base/scalar.) of the #251 still needs to be done in order to complete the issue/bounty.

**Comment by winrhcp** [comment]
> Thank you! Looks good!
> 
> @winrhcp just to be extra clear: the second task (Move the Scalar trait to its own "scalar" file within base/scalar.) of the #234 still needs to be done in order to complete the issue/bounty.

I'm new to Rust and would appreciate more explanation or an example for how to move the Scalar trait to its own 'scalar' file within base/scalar to ensure I handle it correctly.

**Pull request merged**
