### PR TITLE
refactor: enable `clippy::pedantic` lint group

### LINKED ISSUE #182: Enable `clippy::pedantic` lint group.
# Background and Motivation
We have `cargo clippy` running in our CI in order to enforce code quality. In order to increase our standards, we should enable the `clippy::pedantic` lint group.

# Requested Changes
- [ ] Add the `clippy::pedantic` lint to the bottom of the workspace `Cargo.toml` file.
- [ ] Refactor all of the code warnings so that clippy will pass.

NOTE: `clippy::pedantic` is very aggressive. It is possible that we will want to blanket `allow` some lints.

NOTE: please have good git hygiene on this issue. Make sure the individual commits on a PR are small and individually readable.

### PR DESCRIPTION
**Pull request by mehulmathur16**
# Rationale for this change

We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.

# What changes are included in this PR?

This PR adds pedantic lint check to the toml file, replacing the existing individual lint checks that are part of pedantic group.

# Are these changes tested?

Yes.

/fixes #182 
/claim #182

### CODE REVIEW

**Comment by mehulmathur16** [comment]
@JayWhite2357 Can you please review this PR ?

**Review by JayWhite2357 — APPROVED** [review]
Looks good. Thanks for all the work on this one!

**Comment by JayWhite2357** [comment]
/tip $100
Thanks for the attention to detail on this issue and sticking with it! This will be great in ensuring high code quality going forward.

**Comment by mehulmathur16** [comment]
Thank you! I'm glad we could get this done. It’s been great working with you and @iajoiner on this. Looking forward to more contributions!

**Pull request merged**
